import { useState, useEffect } from "react";
import { MultiSelect } from "react-multi-select-component";
const options = [
  { label: "3M", value: "3M" },
  { label: "Ability Dynamics", value: "Ability Dynamics" },
  { label: "Aircast", value: "Aircast" },
  { label: "Allard", value: "Allard" },
  { label: "Alps", value: "Alps" },
  {
    label: "American Prosthetic Components",
    value: "American Prosthetic Components",
  },
  { label: "APC", value: "APC" },
  { label: "Aryse", value: "Aryse" },
  { label: "ASAP", value: "ASAP" },
  { label: "Aspen", value: "Aspen" },
  { label: "Athletic", value: "Athletic" },
  { label: "Avalon", value: "Avalon" },
  { label: "Axtion", value: "Axtion" },
  { label: "Becker", value: "Becker" },
  { label: "BioQuest", value: "BioQuest" },
  { label: "BioSkin", value: "BioSkin" },
  { label: "Blatchford", value: "Blatchford" },
  { label: "BraceSox", value: "BraceSox" },
  { label: "Breg", value: "Breg" },
  { label: "Bulldog", value: "Bulldog" },
  { label: "Catech Inc", value: "Catech Inc" },
  { label: "Century Innovations", value: "Century Innovations" },
  { label: "College Park", value: "College Park" },
  { label: "Comfort Products", value: "Comfort Products" },
  { label: "Comfortland", value: "Comfortland" },
  { label: "CPI", value: "CPI" },
  { label: "Cypress Adaptive", value: "Cypress Adaptive " },
  { label: "DAW", value: "DAW" },
  { label: "DeRoyal", value: "DeRoyal" },
  { label: "DJO", value: "DJO" },
  { label: "Donjoy", value: "Donjoy" },
  { label: "Dr Comfort", value: "Dr Comfort" },
  { label: "Dr Scholls", value: "Dr Scholls" },
  { label: "Drive", value: "Drive" },
  { label: "Durasleeve", value: "Durasleeve" },
  { label: "Elan", value: "Elan" },
  { label: "Encore", value: "Encore" },
  { label: "Endolite", value: "Endolite" },
  { label: "ESP", value: "ESP" },
  { label: "Evolution Industries", value: "Evolution Industries" },
  { label: "Fabtech", value: "Fabtech" },
  { label: "Fillauer", value: "Fillauer" },
  { label: "Flex Foot", value: "Flex Foot" },
  { label: "Freedom Innovation", value: "Freedom Innovation" },
  { label: "Freeman", value: "Freeman" },
  { label: "GPF", value: "GPF" },
  { label: "Hanger", value: "Hanger" },
  { label: "Hely & Weber", value: "Hely %26 Weber" },
  { label: "Hosmer", value: "Hosmer" },
  { label: "IN Prosthetic Components", value: "In Prosthetic Components" },
  { label: "Jack Mart", value: "Jack Mart" },
  { label: "Juzo", value: "Juzo" },
  { label: "Kingsley", value: "Kingsley" },
  { label: "Kintera", value: "Kintera" },
  { label: "KISS", value: "KISS" },
  { label: "Knit-rite", value: "Knit-rite" },
  { label: "Leg Works", value: "Leg Works" },
  { label: "MAKstride", value: "MAKstride" },
  { label: "Mauch", value: "Mauch" },
  { label: "Maverick", value: "Maverick" },
  { label: "MedChoice", value: "MedChoice" },
  { label: "Medex", value: "Medex" },
  { label: "Medi", value: "Medi" },
  { label: "Merrell", value: "Merrell" },
  { label: "Mica", value: "Mica" },
  { label: "Molnlycke", value: "Molnlycke" },
  { label: "New Options Sports", value: "New Options Sports" },
  { label: "no Adapter", value: "no Adapter" },
  { label: "NY Rehab", value: "NY Rehab" },
  { label: "Operation Namaste", value: "Operation Namaste" },
  { label: "Optimus", value: "Optimus" },
  { label: "Orion", value: "Orion" },
  { label: "Ortho Europe LTD", value: "Ortho Europe LTD" },
  { label: "Orthomerica", value: "Orthomerica" },
  { label: "Ossur", value: "Ossur" },
  { label: "Ottobock", value: "Ottobock" },
  { label: "OWW", value: "OWW" },
  { label: "Paceline", value: "Paceline" },
  { label: "PMT", value: "PMT" },
  { label: "Procare", value: "Procare" },
  { label: "Progressive Orthotics", value: "Progressive Orthotics" },
  { label: "Promenade", value: "Promenade" },
  { label: "Promogran", value: "Promogran" },
  { label: "Proteor", value: "Proteor" },
  { label: "Rampro", value: "Rampro" },
  { label: "RCAI", value: "RCAI" },
  { label: "Rooke", value: "Rooke" },
  { label: "Royale Flush", value: "Royal Flush" },
  { label: "Royale Knit", value: "Royale Knit" },
  { label: "Saucony", value: "Saucony" },
  { label: "Silipos", value: "Silipos" },
  { label: "Sketchers", value: "Sketchers" },
  { label: "Spalding", value: "Spalding" },
  { label: "SPS", value: "SPS" },
  { label: "SRT P&O", value: "SRT P%26O" },
  { label: "ST&G", value: "ST%26G" },
  { label: "Streifeneder", value: "Streifeneder" },
  { label: "Swede-O", value: "Swede-O" },
  { label: "Syncor", value: "Syncor" },
  { label: "Teh Lin Pros. & Ortho.", value: "Teh Lin Pros. %26 Ortho." },
  { label: "Thuasne", value: "Thuasne" },
  { label: "TiMed", value: "TiMed" },
  { label: "Titan", value: "TItan" },
  { label: "Townsend", value: "Townsend" },
  { label: "Trail Blazer", value: "Trail Blazer" },
  { label: "Trulife", value: "Trulife" },
  { label: "TruVue", value: "TruVue" },
  { label: "Uni Roch.", value: "Uni Roch." },
  { label: "UNIPROX", value: "UNIPROX" },
  { label: "United Ortho", value: "United Ortho" },
  { label: "US Orthotics", value: "US Orthotics" },
  { label: "Various", value: "Various" },
  { label: "Willow Wood", value: "Willow Wood" },
  { label: "Win Walker", value: "Win Walker" },
  { label: "Wright & Filipps", value: "Wright %26 Filipps" },
];

const options2 = [
  { label: "AAFO", value: "AAFO" },
  { label: "ADB", value: "ADB" },
  { label: "ADU", value: "ADU" },
  { label: "AFT", value: "AFT" },
  { label: "AKA", value: "AKA" },
  { label: "ANCH", value: "ANCH" },
  { label: "ANK", value: "ANK" },
  { label: "ANKBLK", value: "ANKBLK" },
  { label: "ANKL", value: "ANKL" },
  { label: "APD", value: "APD" },
  { label: "ARA", value: "ARA" },
  { label: "ARM", value: "ARM" },
  { label: "ASA", value: "ASA" },
  { label: "ASAP", value: "ASAP" },
  { label: "ASC", value: "ASC" },
  { label: "ATC", value: "ATC" },
  { label: "ATST", value: "ATST" },
  { label: "BB", value: "BB" },
  { label: "BBALL", value: "BBALL" },
  { label: "BKARD", value: "BKARD" },
  { label: "BP", value: "BP" },
  { label: "BRACE-F", value: "BRACE-F" },
  { label: "BSUP", value: "BSUP" },
  { label: "CASTL", value: "CASTL" },
  { label: "CIRC", value: "CIRC" },
  { label: "CL", value: "CL" },
  { label: "COSCOV", value: "COSCOV" },
  { label: "CROR", value: "CROR" },
  { label: "CRUTCH", value: "CRUTCH" },
  { label: "CTSB", value: "CTSB" },
  { label: "EXP", value: "EXP" },
  { label: "FER", value: "FER" },
  { label: "GLS", value: "GLS" },
  { label: "GSHEET", value: "GSHEET" },
  { label: "HANDS-C", value: "HANDS-C" },
  { label: "HIPP", value: "HIPP" },
  { label: "HJ", value: "HJ" },
  { label: "HPIL", value: "HPIL" },
  { label: "INSOLE", value: "INSOLE" },
  { label: "KB", value: "KB" },
  { label: "KBL", value: "KBL" },
  { label: "KBR", value: "KBR" },
  { label: "KC", value: "KC" },
  { label: "KCAP", value: "KCAP" },
  { label: "KH", value: "KH" },
  { label: "KIMB", value: "KIMB" },
  { label: "KMAN", value: "KMAN" },
  { label: "KMECH", value: "KMECH" },
  { label: "KN", value: "KN" },
  { label: "KP", value: "KP" },
  { label: "KUID", value: "KUID" },
  { label: "LAK", value: "LAK" },
  { label: "LANY", value: "LANY" },
  { label: "LB", value: "LB" },
  { label: "LBK", value: "LBK" },
  { label: "LBL", value: "LBL" },
  { label: "LBR", value: "LBR" },
  { label: "LDUM", value: "LDUM" },
  { label: "Leg Storage Rack", value: "Leg Storage Rack" },
  { label: "LF", value: "LF" },
  { label: "LFP", value: "LFP" },
  { label: "LFS", value: "LFS" },
  { label: "LL", value: "LL" },
  { label: "LSHELL", value: "LSHELL" },
  { label: "LSHOE", value: "LSHOE" },
  { label: "LSKT", value: "LSKT" },
  { label: "LSP", value: "LSP" },
  { label: "LUMB", value: "LUMB" },
  { label: "MCL", value: "MCL" },
  { label: "MISC", value: "MISC" },
  { label: "MMED", value: "MMED" },
  { label: "MOD", value: "MOD" },
  { label: "NLS", value: "NLS" },
  { label: "OBH", value: "OBH" },
  { label: "OP", value: "OP" },
  { label: "PIN", value: "PIN" },
  { label: "PYAPD", value: "PYAPD" },
  { label: "PYC", value: "PYC" },
  { label: "PYIC", value: "PYIC" },
  { label: "PYL", value: "PYL" },
  { label: "PYS", value: "PYS" },
  { label: "RAFO", value: "RAFO" },
  { label: "RAK", value: "RAK" },
  { label: "RBK", value: "RBK" },
  { label: "RF", value: "RF" },
  { label: "RFP", value: "RFP" },
  { label: "RFS", value: "RFS" },
  { label: "RH", value: "RH" },
  { label: "RHC", value: "RHC" },
  { label: "RNECK", value: "RNECK" },
  { label: "RSHELL", value: "RSHELL" },
  { label: "RSHOE", value: "RSHOE" },
  { label: "RUN", value: "RUN" },
  { label: "SBELT", value: "SBELT" },
  { label: "SCON", value: "SCON" },
  { label: "SCREW", value: "SCREW" },
  { label: "SHOE", value: "SHOE" },
  { label: "SIMB", value: "SIMB" },
  { label: "SKSL", value: "SKSL" },
  { label: "SKT", value: "SKT" },
  { label: "SKT-C", value: "SKT-C" },
  { label: "SL", value: "SL" },
  { label: "SOCK", value: "SOCK" },
  { label: "SP", value: "SP" },
  { label: "SR", value: "SR" },
  { label: "SRL", value: "SRL" },
  { label: "SSG", value: "SSG" },
  { label: "SSL", value: "SSL" },
  { label: "SSN", value: "SSN" },
  { label: "STSH", value: "STSH" },
  { label: "TFR", value: "TFR" },
  { label: "TOR", value: "TOR" },
  { label: "TR", value: "TR" },
  { label: "UAF", value: "UAF" },
  { label: "UEL", value: "UEL" },
  { label: "UF", value: "UF" },
  { label: "UFP", value: "UFP" },
  { label: "VAC", value: "VAC" },
  { label: "VIP", value: "VIP" },
  { label: "VLV", value: "VLV" },
  { label: "VLVP", value: "VLVP" },
  { label: "VOID", value: "VOID" },
  { label: "WBOOT", value: "WBOOT" },
  { label: "WRST", value: "WRST" },
];

const MultipleSelect = ({ selectedManufacturer, setSelectedManufacturer, selectedSKU, setSelectedSKU }) => {
  return (
    <>
      <div style={{ width: "80%", margin: "0 20px 20px 20px" }}>
        <h1>Select Manufacturer</h1>
        <MultiSelect
          options={options}
          value={selectedManufacturer}
          onChange={setSelectedManufacturer}
          labelledBy="Select"
        />
      </div> 
      <div style={{ width: "80%", margin: "0 20px 20px 20px" }}>
        <h1>Select SKU</h1>
        <MultiSelect
          options={options2}
          value={selectedSKU}
          onChange={setSelectedSKU}
          labelledBy="Select"
        />
      </div>
    </>
  );
};

export default MultipleSelect;
